language: haskell
ghc:
  - 7.8
  - 7.6
before_install: # install latest happy deb from a PPA
  - sudo add-apt-repository -y ppa:hvr/ghc
  - sudo apt-get update
  - sudo apt-get install happy-1.19.4
  - export PATH=/opt/happy/1.19.4/bin:$PATH
install:
  - cabal sandbox init
  - cabal sandbox add-source haxr-browser
  - cabal sandbox add-source opennebula
  - cabal install --only-dependencies --enable-tests # install also deps for testing
notifications:
  email:
    on_success: always
    on_failure: always
  slack: envisage:Y39mhzPxnESyhZUwrPXeJzij
