# NB: don't set `language: haskell` here
language: c

env:
 - CABALVER=1.18 GHCVER=7.6.3
 - CABALVER=1.18 GHCVER=7.8.4
 - CABALVER=1.20 GHCVER=7.8.4
 - CABALVER=1.22 GHCVER=7.10.1

before_install:
 - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH

install:
 - travis_retry sudo apt-get install happy-1.19.4 alex-3.1.3
 - export PATH=/opt/alex/3.1.3/bin:/opt/happy/1.19.4/bin:$PATH
 - cabal --version
 - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
 - cabal sandbox init
 - cabal sandbox update
 - cabal sandbox add-source haxr-browser
 - cabal sandbox add-source opennebula
 - cabal install --only-dependencies
 - wget https://github.com/BNFC/bnfc/releases/download/v2.7.1/BNFC-2.7.1-linux-x86_64.tar.gz
 - tar -xzf BNFC-2.7.1-linux-x86_64.tar.gz
 - sudo cp BNFC-2.7.1-linux-x86_64/bin/bnfc /usr/bin

script:
 - if [ -f configure.ac ]; then autoreconf -i; fi
 - cabal configure -v2
 - cabal build && make grammar && cd test && ./test_grammar.sh

notifications:
  email:
    on_success: never
    on_failure: change
  slack: envisage:Y39mhzPxnESyhZUwrPXeJzij
