language: haskell
ghc:
  - 7.8
  - 7.6
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq happy # haskell-src-exts requires happy
install:
  - cabal sandbox init
  - cabal sandbox add-source haxr-browser
  - cabal sandbox add-source opennebula
  - cabal install --only-dependencies --enable-tests # install also deps for testing
